_BASE_: [
  './_base_/models/fcos_r50_fpn.yml',
  './_base_/optimizers/rcnn_1x.yml',
  './_base_/datasets/coco_detection.yml',
  './_base_/readers/fcos_fpn_reader.yml',
  './_base_/runtime.yml',
]

pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
weights: output/fcos_dcn_r50_fpn_1x/model_final

ResNet:
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [1,2,3]
  num_stages: 4
  dcn_v2_stages: [1,2,3]

FCOSHead:
  fcos_feat:
    name: FCOSFeat
    feat_in: 256
    feat_out: 256 
    num_convs: 4
    norm_type: "gn"
    use_dcn: true
  num_classes: 80
  fpn_stride: [8, 16, 32, 64, 128]
  prior_prob: 0.01
  fcos_loss: FCOSLoss
  norm_reg_targets: true
  centerness_on_reg: true
